repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26 # v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: gitlint
        name: gitlint
        entry: poetry run gitlint
        args: [--staged, --msg-filename]
        language: system
        stages: [commit-msg]
-   repo: local
    hooks:
    -   id: mdformat
        name: mdformat
        entry: poetry run mdformat
        args: [--wrap, '80', --check]
        language: system
        types: [markdown]
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        args: [--line-length, '80', --check]
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: markdownlint
        name: markdownlint
        entry: ./node_modules/.bin/markdownlint
        language: system
        types: [markdown]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types: [python]
